services:
  chain-server:
    container_name: chain-server
    image: chain-server:latest
    build:
      context: ../../
      dockerfile: ./RetrievalAugmentedGeneration/Dockerfile
      args:
        EXAMPLE_NAME: chinese_rag
    command: --port 8081 --host 0.0.0.0
    environment:
      APP_VECTORSTORE_URL: "http://milvus:19530"
      APP_VECTORSTORE_NAME: "milvus"
      APP_LLM_MODELNAME: ai-llama3-70b
      APP_LLM_MODELENGINE: nvidia-ai-endpoints
      APP_LLM_SERVERURL: ${APP_LLM_SERVERURL:-""}
      APP_EMBEDDINGS_MODELNAME: ${APP_EMBEDDINGS_MODELNAME:-BAAI/bge-large-zh-v1.5}
      APP_EMBEDDINGS_MODELENGINE: huggingface
      APP_EMBEDDINGS_SERVERURL: ${APP_EMBEDDINGS_SERVERURL:-""}
      APP_TEXTSPLITTER_MODELNAME: ${APP_EMBEDDINGS_MODELNAME:-BAAI/bge-large-zh-v1.5}
      APP_TEXTSPLITTER_CHUNKSIZE: 510
      APP_TEXTSPLITTER_CHUNKOVERLAP: 200
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      APP_PROMPTS_CHATTEMPLATE: "您是一个有用、尊重和诚实的助手。请始终尽可能有帮助地回答问题，同时确保安全。请确保您的回答本质上是积极的。"
      APP_PROMPTS_RAGTEMPLATE: "你是一个名叫Envie的有用的AI助手。你只根据所提供的上下文回答问题。如果有些内容超出了上下文，你将避免回答，并礼貌地拒绝回应用户。"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-api}
      COLLECTION_NAME: nvidia_api_catalog
      APP_RETRIEVER_TOPK: 4
      APP_RETRIEVER_SCORETHRESHOLD: 0.25
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      ENABLE_TRACING: false
    volumes:
      - ${MODEL_CACHE_DIR:-./hf_models}:/models
      - ${PDF_CACHE_DIR:-./tmp_pdfs}:/pdfs
    ports:
    - "8081:8081"
    expose:
    - "8081"
    shm_size: 5gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  rag-playground:
    container_name: rag-playground
    image: rag-playground:latest
    build:
      context: ../.././RetrievalAugmentedGeneration/frontend/
      dockerfile: Dockerfile
    command: --port 8090
    environment:
      APP_SERVERURL: http://chain-server
      APP_SERVERPORT: 8081
      APP_MODELNAME: yi_34b
      RIVA_API_URI: ${RIVA_API_URI:-}
      RIVA_API_KEY: ${RIVA_API_KEY:-}
      RIVA_FUNCTION_ID: ${RIVA_FUNCTION_ID:-}
      TTS_SAMPLE_RATE: ${TTS_SAMPLE_RATE:-48000}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      ENABLE_TRACING: false
    volumes:
      - ${DOCKER_CACHE_DIR:-./tmp}:/tmp
      - ${PDF_CACHE_DIR:-./tmp_pdfs}:/app/frontend/static/pdfs
    ports:
    - "8090:8090"
    expose:
    - "8090"
    depends_on:
    - chain-server

  pdf-parser:
    container_name: pdf-parser
    image: pdf-parser:latest
    build:
      context: ../.././RetrievalAugmentedGeneration/pdf/
      dockerfile: Dockerfile
    command: --port 8088 --host 0.0.0.0
    environment:
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
    volumes:
      - ${PDF_CACHE_DIR:-./tmp_pdfs}:/pdfs
    ports:
    - "8088:8088"
    expose:
    - "8088"
    # depends_on:
    # - chain-server

networks:
  default:
    name: nvidia-rag
